// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using GolfSweep.Data;

namespace GolfSweep.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20191110160203_InitialClasses")]
    partial class InitialClasses
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Sweep.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Sweep.Data.Entry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("EventId");

                    b.Property<bool>("Paid");

                    b.Property<Guid?>("PlayerId");

                    b.Property<Guid?>("ScoreCardId");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("ScoreCardId");

                    b.ToTable("Entries");
                });

            modelBuilder.Entity("Sweep.Data.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("Date");

                    b.Property<Guid?>("SweepId");

                    b.HasKey("Id");

                    b.HasIndex("SweepId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Sweep.Data.Handicap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("Created");

                    b.Property<double>("Exact");

                    b.Property<Guid>("PlayerId");

                    b.Property<int>("Playing");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("Handicaps");
                });

            modelBuilder.Entity("Sweep.Data.Hole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Index");

                    b.Property<int>("Number");

                    b.Property<int>("Par");

                    b.Property<int>("Points");

                    b.Property<int>("Score");

                    b.HasKey("Id");

                    b.ToTable("Holes");
                });

            modelBuilder.Entity("Sweep.Data.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Sweep.Data.Result", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("EventId");

                    b.Property<Guid?>("SecondId");

                    b.Property<Guid?>("ThirdId");

                    b.Property<Guid?>("WinnerId");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("SecondId");

                    b.HasIndex("ThirdId");

                    b.HasIndex("WinnerId");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("Sweep.Data.ScoreCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("EighthId");

                    b.Property<Guid?>("EithteenthId");

                    b.Property<Guid?>("EleventhId");

                    b.Property<Guid?>("EventId");

                    b.Property<Guid?>("FifteenthId");

                    b.Property<Guid?>("FifthId");

                    b.Property<Guid?>("FirstId");

                    b.Property<Guid?>("FourteenthId");

                    b.Property<Guid?>("FourthId");

                    b.Property<Guid?>("NinthId");

                    b.Property<Guid>("PlayerId");

                    b.Property<Guid?>("SecondId");

                    b.Property<Guid?>("SeventeenthId");

                    b.Property<Guid?>("SeventhId");

                    b.Property<Guid?>("SixteenthId");

                    b.Property<Guid?>("SixthId");

                    b.Property<Guid?>("TenthId");

                    b.Property<Guid?>("ThirdId");

                    b.Property<Guid?>("ThirteenthId");

                    b.Property<Guid?>("TwelwthId");

                    b.HasKey("Id");

                    b.HasIndex("EighthId");

                    b.HasIndex("EithteenthId");

                    b.HasIndex("EleventhId");

                    b.HasIndex("EventId");

                    b.HasIndex("FifteenthId");

                    b.HasIndex("FifthId");

                    b.HasIndex("FirstId");

                    b.HasIndex("FourteenthId");

                    b.HasIndex("FourthId");

                    b.HasIndex("NinthId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SecondId");

                    b.HasIndex("SeventeenthId");

                    b.HasIndex("SeventhId");

                    b.HasIndex("SixteenthId");

                    b.HasIndex("SixthId");

                    b.HasIndex("TenthId");

                    b.HasIndex("ThirdId");

                    b.HasIndex("ThirteenthId");

                    b.HasIndex("TwelwthId");

                    b.ToTable("ScoreCards");
                });

            modelBuilder.Entity("Sweep.Data.Sweep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("Created");

                    b.Property<string>("Name");

                    b.Property<string>("OwnerId");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Sweeps");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Sweep.Data.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Sweep.Data.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Sweep.Data.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Sweep.Data.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Sweep.Data.Entry", b =>
                {
                    b.HasOne("Sweep.Data.Event")
                        .WithMany("Entries")
                        .HasForeignKey("EventId");

                    b.HasOne("Sweep.Data.Player")
                        .WithMany("Entries")
                        .HasForeignKey("PlayerId");

                    b.HasOne("Sweep.Data.ScoreCard", "ScoreCard")
                        .WithMany()
                        .HasForeignKey("ScoreCardId");
                });

            modelBuilder.Entity("Sweep.Data.Event", b =>
                {
                    b.HasOne("Sweep.Data.Sweep")
                        .WithMany("Events")
                        .HasForeignKey("SweepId");
                });

            modelBuilder.Entity("Sweep.Data.Handicap", b =>
                {
                    b.HasOne("Sweep.Data.Player", "Player")
                        .WithMany("Handicaps")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Sweep.Data.Player", b =>
                {
                    b.HasOne("Sweep.Data.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Sweep.Data.Result", b =>
                {
                    b.HasOne("Sweep.Data.Event", "Event")
                        .WithOne("Result")
                        .HasForeignKey("Sweep.Data.Result", "EventId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Sweep.Data.ScoreCard", "Second")
                        .WithMany()
                        .HasForeignKey("SecondId");

                    b.HasOne("Sweep.Data.ScoreCard", "Third")
                        .WithMany()
                        .HasForeignKey("ThirdId");

                    b.HasOne("Sweep.Data.ScoreCard", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerId");
                });

            modelBuilder.Entity("Sweep.Data.ScoreCard", b =>
                {
                    b.HasOne("Sweep.Data.Hole", "Eighth")
                        .WithMany()
                        .HasForeignKey("EighthId");

                    b.HasOne("Sweep.Data.Hole", "Eithteenth")
                        .WithMany()
                        .HasForeignKey("EithteenthId");

                    b.HasOne("Sweep.Data.Hole", "Eleventh")
                        .WithMany()
                        .HasForeignKey("EleventhId");

                    b.HasOne("Sweep.Data.Event")
                        .WithMany("Cards")
                        .HasForeignKey("EventId");

                    b.HasOne("Sweep.Data.Hole", "Fifteenth")
                        .WithMany()
                        .HasForeignKey("FifteenthId");

                    b.HasOne("Sweep.Data.Hole", "Fifth")
                        .WithMany()
                        .HasForeignKey("FifthId");

                    b.HasOne("Sweep.Data.Hole", "First")
                        .WithMany()
                        .HasForeignKey("FirstId");

                    b.HasOne("Sweep.Data.Hole", "Fourteenth")
                        .WithMany()
                        .HasForeignKey("FourteenthId");

                    b.HasOne("Sweep.Data.Hole", "Fourth")
                        .WithMany()
                        .HasForeignKey("FourthId");

                    b.HasOne("Sweep.Data.Hole", "Ninth")
                        .WithMany()
                        .HasForeignKey("NinthId");

                    b.HasOne("Sweep.Data.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Sweep.Data.Hole", "Second")
                        .WithMany()
                        .HasForeignKey("SecondId");

                    b.HasOne("Sweep.Data.Hole", "Seventeenth")
                        .WithMany()
                        .HasForeignKey("SeventeenthId");

                    b.HasOne("Sweep.Data.Hole", "Seventh")
                        .WithMany()
                        .HasForeignKey("SeventhId");

                    b.HasOne("Sweep.Data.Hole", "Sixteenth")
                        .WithMany()
                        .HasForeignKey("SixteenthId");

                    b.HasOne("Sweep.Data.Hole", "Sixth")
                        .WithMany()
                        .HasForeignKey("SixthId");

                    b.HasOne("Sweep.Data.Hole", "Tenth")
                        .WithMany()
                        .HasForeignKey("TenthId");

                    b.HasOne("Sweep.Data.Hole", "Third")
                        .WithMany()
                        .HasForeignKey("ThirdId");

                    b.HasOne("Sweep.Data.Hole", "Thirteenth")
                        .WithMany()
                        .HasForeignKey("ThirteenthId");

                    b.HasOne("Sweep.Data.Hole", "Twelwth")
                        .WithMany()
                        .HasForeignKey("TwelwthId");
                });

            modelBuilder.Entity("Sweep.Data.Sweep", b =>
                {
                    b.HasOne("Sweep.Data.ApplicationUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId");
                });
#pragma warning restore 612, 618
        }
    }
}
